#!/usr/bin/env ruby

require 'rmeetup'
require 'time'
require 'csv'

event_id = ARGV[0]  # Meetup event ID
host_name = ARGV[1] # Full name of the host of the event
meetup_api_key = ENV['MEETUP_API_KEY']

client = RMeetup::Client.new do |config|
  config.api_key = meetup_api_key
end

results = client.fetch(:rsvps, { event_id: event_id, rsvp: 'yes', fields: ['event'] })

# Meetup time = millis from epoc as a string, Envoy wants 2016-10-12 6:00 PM
def format_time(time)
  Time.at(time.to_i / 1000).strftime('%Y-%m-%d %I:%M %p')
end

CSV.open("meetup-#{event_id}.csv", "wb") do |csv|
  csv << ['invitee_name*', 'invitee_email', 'expected_arrival_time*', 'private_notes', 'host_name',
    'Purpose of visit*', 'Your Company', 'Licence Plate (If using guest parking)']
  results.each do |row|
    member = row.rsvp['member']
    event_start = format_time(row.rsvp['event']['time'])
    csv << [member['name'], '', event_start, '', host_name, 'Meeting', '', '']
  end
end
