#!/usr/bin/env ruby

require 'rmeetup'
require 'time'
require 'csv'

client = RMeetup::Client.new do |config|
  config.api_key = ENV['MEETUP_API_KEY']
end
event_id = 234262445 # TODO, read from argument

results = client.fetch(:rsvps, { event_id: event_id, rsvp: 'yes', fields: ['event'] })

# Meetup time = millis from epoc as a string
def format_time(time)
  Time.at(time.to_i / 1000).strftime('%Y-%m-%d %I:%M %p')
end

CSV.open("meetup-#{event_id}.csv", "wb") do |csv|
  csv << ['invitee_name*', 'invitee_email', 'expected_arrival_time*', 'private_notes', 'host_name', 'Purpose of visit*', 'Your Company', 'Licence Plate (If using guest parking)']
  results.each do |rsvp|
    member = rsvp.rsvp['member']
    event_start = format_time(rsvp.rsvp['event']['time'])
    csv << [member['name'], '', event_start, '', 'Richard Paul', 'Meeting', '', '']
  end
end
